### ISSUE TITLE
Crawler excludes user type repos

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-backend#112]
Right now, the crawler is designed to support 2 kinds of feeds:
1. org URL (such as `github.com/org-name`)
2. Single repository URL

As such, it is not possible to provide a list of user names containing repos to crawl since the API call used is exclusively retrieving the list of repositories belonging to the org and not to the user (`GET /orgs/:org/repos` and not `GET /users/:username/repos`). 

I believe this choice is rather limiting the scope of the crawler since it may not be always feasible to obtain a URL pointing to an org and the cost of migrating every repository already prepared from a user to an org may be != 0 for some stakeholder. 

As such, I believe it could be easier to check the type of the user and modify that API call correspondingly. 

This check can be as easy as parsing the JSON response of GET /users/:username which contains the `type`:
```
GET /users/libremente
{ 
"type": "User"
}

GET /users/italia
{
"type": "Organization"
}
```

What do you think? @sebbalex @alranel

**Comment by libremente** [comment]
As discussed with @alranel, the crawler should also handle user types. @sebbalex

**Comment by sebbalex** [comment]
The real problem was [here](https://github.com/italia/developers-italia-backend/blob/e8783570794edda42d6aabb8bbd246caa830e3ef/crawler/crawler/github.go#L274), whether querying api for one of repositories inside an organisation or user returns an error that `return` caused exit from repositories loop and skipping the evaluation of others repo in list.
