### ISSUE TITLE
Gitlab raw URL breaks the validation

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-backend#192]
On some versions of gitlab, the raw URL is form as follows:
```https://gitlab.fuss.bz.it/fuss/fuss-metadata/-/raw/master/```

as such, most probably the `-` (dash) breaks the validation.
See this for example:
```
url: declared url (https://gitlab.fuss.bz.it/fuss/fuss-metadata) does not match the actual publiccode.yml source URL (https://gitlab.fuss.bz.it/fuss/fuss-metadata/-/raw/master/)
```

**Comment by libremente** [comment]
Linked to https://github.com/italia/publiccode-parser-go/issues/40

**Comment by bfabio** [comment]
The general case should be fixed by the fix in alranel/go-vcsurl#4, but even with that fix in this case the GitLab API returns the list of repos with the HTTP protocol (not HTTPS) in the URL. The crawler ends up comparing `https://gitlab.fuss.bz.it/fuss/fuss-metadata` to `http://gitlab.fuss.bz.it/fuss/fuss-metadata`, note the different protocols.

That's probably due to that instance's configuration and the redirect to HTTPS being handled at the webserver level: not ideal, but not the end of the world either.

We should consider relaxing that check and consider HTTP and HTTPS URLs as the same repo. @libremente, @sebbalex wdyt? 

Related to italia/publiccode-parser-go#55

**Comment by sebbalex** [comment]
> We should consider relaxing that check and consider HTTP and HTTPS URLs as the same repo.

I can't see others viable ways and as you already mention, is not the end of the world.

**Comment by bfabio** [comment]
#199 contains the fix for this as well
