### ISSUE TITLE
Crawler did not find 3 days modification to gcompris PublicCode.yml 

### ISSUE THREAD

**Issue by allon49** [italia/developers-italia-backend#212]
Crawler did not find 3 days modification to gcompris PublicCode.yml. 
We can not see the screenshot added to this page:
https://developers.italia.it/it/software/education-gcompris-8b38a5

**Comment by bfabio** [comment]
Thanks @allon49, going to look into it ASAP.

**Comment by bfabio** [comment]
@allon49 looks like the new file doesn't validate:

```
$ docker run -i italia/publiccode-parser-go  https://invent.kde.org/education/gcompris/-/raw/master/publiccode.yml
validation ko:
description/en/screenshots: Absolute URL (https://gcompris.net/screenshots_qt/large/root.png) is outside the repository (https://invent.kde.org/education/gcompris/-/raw/master/)
description/it/screenshots: Absolute URL (https://gcompris.net/screenshots_qt/large/root.png) is outside the repository (https://invent.kde.org/education/gcompris/-/raw/master/)
```

**Comment by allon49** [comment]
Hi,
Thanks for the information, I will tell our web maintainer and add this to our step by step user guide on how to add kde softwares to the catalog.
Is there a way for user applying to the catalog to find on their own this kind of failure?
Regards,

**Comment by allon49** [comment]
I put your validation process inside our step by step guide, so there is maybe no need to have a mail getting back errors, at least for kde.

**Comment by libremente** [comment]
> Hi,
> Thanks for the information, I will tell our web maintainer and add this to our step by step user guide on how to add kde softwares to the catalog.

This is great news @allon49! Can we take a look at it in order to provide some feedback? Thanks for the great effort!

> Is there way for user applying to the catalog to find on their own this kind of failure without running docker publiccode-parser-go? Maybe an email is sent to the site maintainer (the one present in publiccode)?

We are currently working on a automation which basically opens an issue every time a validation problem occurs. 
However, my suggestion is to insert the validation inside your preferred CI (see this: https://github.com/italia/publiccode-parser-go#easy-validation-with-docker) in order to be warned when problems occur. 
For example, [here](https://gitlab.com/comune-di-ala/openagenda/-/blob/master/.gitlab-ci.yml#L104-108) you can see how an Italian Public Administration is using such an approach.
If someone is using CircleCI, you could implement https://github.com/italia/publiccode-parser-orb or in the GH Actions case there is also https://github.com/italia/publiccode-parser-action. 
Let us know how can we further help you out!

Thanks a lot :rocket:

**Comment by allon49** [comment]
Hi,
Screenshots are still not showing up. I checked the validity of our publiccode.yml, and the online validator does not see any problem.
https://developers.italia.it/en/software/education-gcompris-8b38a5
Regards,
Emmanuel

**Comment by bfabio** [comment]
@allon49

The issue was fixed by https://invent.kde.org/education/gcompris/-/commit/adfd4a1a897fe85060e678ca74cd7fbaf5e94996, thanks @ruphy!
